name: Release

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         submodules: recursive

      - name: Copy readme
        run: |
          cp ./doc/win-readme.txt ./build/Rippler_artefacts/Release/readme.txt

      - name: Copy presets
        run: |
          cp -r ./scripts/include/presets ./build/Rippler_artefacts/Release

      - name: Copy mallets
        run: |
          cp -r ./scripts/include/mallets ./build/Rippler_artefacts/Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rippler-win
          path: |
            ./build/Rippler_artefacts/Release/VST3
            ./build/Rippler_artefacts/Release/presets
            ./build/Rippler_artefacts/Release/mallets
            ./build/Rippler_artefacts/Release/readme.txt

      - name: Install NSIS
        run: choco install nsis -y

      - name: Get version from git tag
        id: version
        run: |
          $tag = "${env:GITHUB_REF}"
          $version = $tag -replace "^refs/tags/v", ""
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run makensis
        working-directory: ./scripts/win
        run: makensis /DVERSION="${{ env.VERSION }}" ./rippler.nsi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: rippler-win-exe
          path: ./scripts/win/*.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-windows]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: rippler-win
          path: artifacts/rippler-win

      - name: Download Windows installer artifact
        uses: actions/download-artifact@v4
        with:
          name: rippler-win-exe
          path: artifacts/rippler-win-exe

      - name: Append tag to artifacts
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}  # Extracts the tag name, e.g., v1.0.0

          # Zip each platform's artifacts with the tag in the name
          cd artifacts
          zip -r rippler-win-${TAG_NAME}.zip rippler-win

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/rippler-win-*.zip
            artifacts/rippler-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
